[package]
name = "hexapawn"
version = "0.1.0"
authors = ["debilausaure <flovhs59@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4"
rand = "0.7"
rand_pcg = "0.2"
